2012-09-04 18:04:03 Error: [MissingControllerException] Controller class CssController could not be found.
#0 /Applications/MAMP/htdocs/cakeStrap/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2012-09-04 18:22:02 Error: [MissingControllerException] Controller class CssController could not be found.
#0 /Applications/MAMP/htdocs/cakeStrap/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2012-09-04 18:35:02 Error: Fatal Error (4): syntax error, unexpected ')', expecting ',' or ';' in [/Applications/MAMP/htdocs/cakeStrap/app/View/Layouts/default.ctp, line 21]
2012-09-04 18:35:02 Error: [FatalErrorException] syntax error, unexpected ')', expecting ',' or ';'
#0 /Applications/MAMP/htdocs/cakeStrap/lib/Cake/Error/ErrorHandler.php(162): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/Applications/M...', 21)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/Applications/M...', 21, Array)
#2 /Applications/MAMP/htdocs/cakeStrap/lib/Cake/Core/App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/Applications/M...', 21, Array)
#3 /Applications/MAMP/htdocs/cakeStrap/lib/Cake/Core/App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-10-31 17:03:19 Error: Fatal Error (4): syntax error, unexpected 'new' (T_NEW) in [C:\xampp\htdocs\caketeste\app\Model\User.php, line 8]
2012-10-31 17:03:19 Error: [FatalErrorException] syntax error, unexpected 'new' (T_NEW)
#0 C:\xampp\htdocs\caketeste\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 8)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 8, Array)
#2 C:\xampp\htdocs\caketeste\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 8, Array)
#3 C:\xampp\htdocs\caketeste\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-10-31 17:05:50 Error: Fatal Error (4): syntax error, unexpected ')', expecting '(' in [C:\xampp\htdocs\caketeste\app\Model\User.php, line 8]
2012-10-31 17:05:50 Error: [FatalErrorException] syntax error, unexpected ')', expecting '('
#0 C:\xampp\htdocs\caketeste\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 8)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 8, Array)
#2 C:\xampp\htdocs\caketeste\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 8, Array)
#3 C:\xampp\htdocs\caketeste\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-10-31 17:41:23 Error: [MissingViewException] View file "C:\xampp\htdocs\caketeste\app\View\Pages\display.ctp" is missing.
#0 C:\xampp\htdocs\caketeste\lib\Cake\View\View.php(472): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\caketeste\lib\Cake\Controller\Controller.php(957): View->render(NULL, NULL)
#2 C:\xampp\htdocs\caketeste\lib\Cake\Routing\Dispatcher.php(193): Controller->render()
#3 C:\xampp\htdocs\caketeste\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(PagesController), Object(CakeRequest), Object(CakeResponse))
#4 C:\xampp\htdocs\caketeste\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2012-10-31 18:51:48 Error: [MissingViewException] View file "C:\xampp\htdocs\caketeste\app\View\Posts\view.ctp" is missing.
#0 C:\xampp\htdocs\caketeste\lib\Cake\View\View.php(472): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\caketeste\lib\Cake\Controller\Controller.php(957): View->render(NULL, NULL)
#2 C:\xampp\htdocs\caketeste\lib\Cake\Routing\Dispatcher.php(193): Controller->render()
#3 C:\xampp\htdocs\caketeste\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#4 C:\xampp\htdocs\caketeste\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2012-11-14 17:53:40 Error: [MissingViewException] View file "C:\xampp\htdocs\caketeste\app\View\Posts\add.ctp" is missing.
#0 C:\xampp\htdocs\caketeste\lib\Cake\View\View.php(472): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\caketeste\lib\Cake\Controller\Controller.php(957): View->render(NULL, NULL)
#2 C:\xampp\htdocs\caketeste\lib\Cake\Routing\Dispatcher.php(193): Controller->render()
#3 C:\xampp\htdocs\caketeste\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#4 C:\xampp\htdocs\caketeste\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2012-11-14 18:17:24 Error: Fatal Error (4): syntax error, unexpected '<' in [C:\xampp\htdocs\caketeste\app\View\Posts\index.ctp, line 5]
2012-11-14 18:17:25 Error: [FatalErrorException] syntax error, unexpected '<'
#0 C:\xampp\htdocs\caketeste\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 5)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 5, Array)
#2 C:\xampp\htdocs\caketeste\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 5, Array)
#3 C:\xampp\htdocs\caketeste\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-11-27 21:24:31 Error: [MissingConnectionException] Database connection "SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)" is missing, or could not be created.
#0 /Users/tiagolink/Sites/mamp/tiagolink/blog/lib/Cake/Model/Datasource/DboSource.php(260): Mysql->connect()
#1 /Users/tiagolink/Sites/mamp/tiagolink/blog/lib/Cake/Model/ConnectionManager.php(101): DboSource->__construct(Array)
#2 /Users/tiagolink/Sites/mamp/tiagolink/blog/lib/Cake/Model/Model.php(3158): ConnectionManager::getDataSource('default')
#3 /Users/tiagolink/Sites/mamp/tiagolink/blog/lib/Cake/Model/Model.php(1092): Model->setDataSource('default')
#4 /Users/tiagolink/Sites/mamp/tiagolink/blog/lib/Cake/Model/Model.php(3180): Model->setSource('users')
#5 /Users/tiagolink/Sites/mamp/tiagolink/blog/lib/Cake/Model/Model.php(1301): Model->getDataSource()
#6 /Users/tiagolink/Sites/mamp/tiagolink/blog/lib/Cake/View/Helper/FormHelper.php(197): Model->schema()
#7 /Users/tiagolink/Sites/mamp/tiagolink/blog/lib/Cake/View/Helper/FormHelper.php(436): FormHelper->_introspectModel('User', 'fields')
#8 /Users/tiagolink/Sites/mamp/tiagolink/blog/app/View/Elements/form_login.ctp(19): FormHelper->create('User', Array)
#9 /Users/tiagolink/Sites/mamp/tiagolink/blog/lib/Cake/View/View.php(920): include('/Users/tiagolin...')
#10 /Users/tiagolink/Sites/mamp/tiagolink/blog/lib/Cake/View/View.php(883): View->_evaluate('/Users/tiagolin...', Array)
#11 /Users/tiagolink/Sites/mamp/tiagolink/blog/lib/Cake/View/View.php(424): View->_render('/Users/tiagolin...', Array)
#12 /Users/tiagolink/Sites/mamp/tiagolink/blog/app/View/Pages/home.ctp(65): View->element('form_login')
#13 /Users/tiagolink/Sites/mamp/tiagolink/blog/lib/Cake/View/View.php(920): include('/Users/tiagolin...')
#14 /Users/tiagolink/Sites/mamp/tiagolink/blog/lib/Cake/View/View.php(883): View->_evaluate('/Users/tiagolin...', Array)
#15 /Users/tiagolink/Sites/mamp/tiagolink/blog/lib/Cake/View/View.php(475): View->_render('/Users/tiagolin...')
#16 /Users/tiagolink/Sites/mamp/tiagolink/blog/lib/Cake/Controller/Controller.php(957): View->render(NULL, NULL)
#17 /Users/tiagolink/Sites/mamp/tiagolink/blog/lib/Cake/Routing/Dispatcher.php(193): Controller->render()
#18 /Users/tiagolink/Sites/mamp/tiagolink/blog/lib/Cake/Routing/Dispatcher.php(161): Dispatcher->_invoke(Object(PagesController), Object(CakeRequest), Object(CakeResponse))
#19 /Users/tiagolink/Sites/mamp/tiagolink/blog/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#20 {main}
2012-11-27 21:24:34 Error: [MissingControllerException] Controller class JsController could not be found.
#0 /Users/tiagolink/Sites/mamp/tiagolink/blog/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2012-11-27 21:24:50 Error: [MissingControllerException] Controller class JsController could not be found.
#0 /Users/tiagolink/Sites/mamp/tiagolink/blog/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2012-11-27 21:25:03 Error: [MissingControllerException] Controller class JsController could not be found.
#0 /Users/tiagolink/Sites/mamp/tiagolink/blog/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2012-11-27 21:25:11 Error: [MissingControllerException] Controller class JsController could not be found.
#0 /Users/tiagolink/Sites/mamp/tiagolink/blog/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2012-11-27 21:25:16 Error: [MissingControllerException] Controller class JsController could not be found.
#0 /Users/tiagolink/Sites/mamp/tiagolink/blog/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2012-11-27 21:25:35 Error: [MissingControllerException] Controller class JsController could not be found.
#0 /Users/tiagolink/Sites/mamp/tiagolink/blog/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2012-11-27 21:26:49 Error: [MissingControllerException] Controller class JsController could not be found.
#0 /Users/tiagolink/Sites/mamp/tiagolink/blog/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2012-11-27 21:27:06 Error: [MissingControllerException] Controller class PostsController could not be found.
#0 /Users/tiagolink/Sites/mamp/tiagolink/blog/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2012-11-27 21:27:40 Error: [MissingControllerException] Controller class JsController could not be found.
#0 /Users/tiagolink/Sites/mamp/tiagolink/blog/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2012-11-27 21:27:48 Error: [MissingControllerException] Controller class JsController could not be found.
#0 /Users/tiagolink/Sites/mamp/tiagolink/blog/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2012-11-27 22:24:16 Error: [MissingConnectionException] Database connection "SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)" is missing, or could not be created.
#0 C:\xampp\htdocs\blog\lib\Cake\Model\Datasource\DboSource.php(260): Mysql->connect()
#1 C:\xampp\htdocs\blog\lib\Cake\Model\ConnectionManager.php(101): DboSource->__construct(Array)
#2 C:\xampp\htdocs\blog\lib\Cake\Model\Model.php(3158): ConnectionManager::getDataSource('default')
#3 C:\xampp\htdocs\blog\lib\Cake\Model\Model.php(1092): Model->setDataSource('default')
#4 C:\xampp\htdocs\blog\lib\Cake\Model\Model.php(3180): Model->setSource('users')
#5 C:\xampp\htdocs\blog\lib\Cake\Model\Model.php(1301): Model->getDataSource()
#6 C:\xampp\htdocs\blog\lib\Cake\View\Helper\FormHelper.php(197): Model->schema()
#7 C:\xampp\htdocs\blog\lib\Cake\View\Helper\FormHelper.php(436): FormHelper->_introspectModel('User', 'fields')
#8 C:\xampp\htdocs\blog\app\View\Elements\form_login.ctp(19): FormHelper->create('User', Array)
#9 C:\xampp\htdocs\blog\lib\Cake\View\View.php(920): include('C:\xampp\htdocs...')
#10 C:\xampp\htdocs\blog\lib\Cake\View\View.php(883): View->_evaluate('C:\xampp\htdocs...', Array)
#11 C:\xampp\htdocs\blog\lib\Cake\View\View.php(424): View->_render('C:\xampp\htdocs...', Array)
#12 C:\xampp\htdocs\blog\app\View\Pages\home.ctp(65): View->element('form_login')
#13 C:\xampp\htdocs\blog\lib\Cake\View\View.php(920): include('C:\xampp\htdocs...')
#14 C:\xampp\htdocs\blog\lib\Cake\View\View.php(883): View->_evaluate('C:\xampp\htdocs...', Array)
#15 C:\xampp\htdocs\blog\lib\Cake\View\View.php(475): View->_render('C:\xampp\htdocs...')
#16 C:\xampp\htdocs\blog\lib\Cake\Controller\Controller.php(957): View->render(NULL, NULL)
#17 C:\xampp\htdocs\blog\lib\Cake\Routing\Dispatcher.php(193): Controller->render()
#18 C:\xampp\htdocs\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(PagesController), Object(CakeRequest), Object(CakeResponse))
#19 C:\xampp\htdocs\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#20 {main}
2012-11-27 22:25:15 Error: [MissingConnectionException] Database connection "SQLSTATE[HY000] [1049] Unknown database 'caketeste'" is missing, or could not be created.
#0 C:\xampp\htdocs\blog\lib\Cake\Model\Datasource\DboSource.php(260): Mysql->connect()
#1 C:\xampp\htdocs\blog\lib\Cake\Model\ConnectionManager.php(101): DboSource->__construct(Array)
#2 C:\xampp\htdocs\blog\lib\Cake\Model\Model.php(3158): ConnectionManager::getDataSource('default')
#3 C:\xampp\htdocs\blog\lib\Cake\Model\Model.php(1092): Model->setDataSource('default')
#4 C:\xampp\htdocs\blog\lib\Cake\Model\Model.php(3180): Model->setSource('users')
#5 C:\xampp\htdocs\blog\lib\Cake\Model\Model.php(1301): Model->getDataSource()
#6 C:\xampp\htdocs\blog\lib\Cake\View\Helper\FormHelper.php(197): Model->schema()
#7 C:\xampp\htdocs\blog\lib\Cake\View\Helper\FormHelper.php(436): FormHelper->_introspectModel('User', 'fields')
#8 C:\xampp\htdocs\blog\app\View\Elements\form_login.ctp(19): FormHelper->create('User', Array)
#9 C:\xampp\htdocs\blog\lib\Cake\View\View.php(920): include('C:\xampp\htdocs...')
#10 C:\xampp\htdocs\blog\lib\Cake\View\View.php(883): View->_evaluate('C:\xampp\htdocs...', Array)
#11 C:\xampp\htdocs\blog\lib\Cake\View\View.php(424): View->_render('C:\xampp\htdocs...', Array)
#12 C:\xampp\htdocs\blog\app\View\Pages\home.ctp(65): View->element('form_login')
#13 C:\xampp\htdocs\blog\lib\Cake\View\View.php(920): include('C:\xampp\htdocs...')
#14 C:\xampp\htdocs\blog\lib\Cake\View\View.php(883): View->_evaluate('C:\xampp\htdocs...', Array)
#15 C:\xampp\htdocs\blog\lib\Cake\View\View.php(475): View->_render('C:\xampp\htdocs...')
#16 C:\xampp\htdocs\blog\lib\Cake\Controller\Controller.php(957): View->render(NULL, NULL)
#17 C:\xampp\htdocs\blog\lib\Cake\Routing\Dispatcher.php(193): Controller->render()
#18 C:\xampp\htdocs\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(PagesController), Object(CakeRequest), Object(CakeResponse))
#19 C:\xampp\htdocs\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#20 {main}
2012-11-27 23:15:36 Error: [MissingConnectionException] Database connection "SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)" is missing, or could not be created.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Model\Datasource\DboSource.php(260): Mysql->connect()
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Model\ConnectionManager.php(101): DboSource->__construct(Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Model\Model.php(3158): ConnectionManager::getDataSource('default')
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Model\Model.php(1092): Model->setDataSource('default')
#4 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Model\Model.php(3180): Model->setSource('users')
#5 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Model\Model.php(1301): Model->getDataSource()
#6 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\View\Helper\FormHelper.php(197): Model->schema()
#7 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\View\Helper\FormHelper.php(436): FormHelper->_introspectModel('User', 'fields')
#8 C:\xampp\htdocs\Exercicios_PHP\blog\app\View\Elements\form_login.ctp(19): FormHelper->create('User', Array)
#9 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\View\View.php(920): include('C:\xampp\htdocs...')
#10 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\View\View.php(883): View->_evaluate('C:\xampp\htdocs...', Array)
#11 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\View\View.php(424): View->_render('C:\xampp\htdocs...', Array)
#12 C:\xampp\htdocs\Exercicios_PHP\blog\app\View\Pages\home.ctp(65): View->element('form_login')
#13 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\View\View.php(920): include('C:\xampp\htdocs...')
#14 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\View\View.php(883): View->_evaluate('C:\xampp\htdocs...', Array)
#15 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\View\View.php(475): View->_render('C:\xampp\htdocs...')
#16 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Controller\Controller.php(957): View->render(NULL, NULL)
#17 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(193): Controller->render()
#18 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(PagesController), Object(CakeRequest), Object(CakeResponse))
#19 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#20 {main}
2012-11-27 23:18:45 Error: [PDOException] SQLSTATE[HY000]: General error: 1364 Field 'name' doesn't have a default value
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Model\Datasource\DboSource.php(461): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Model\Datasource\DboSource.php(427): DboSource->_execute('INSERT INTO `my...', Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Model\Datasource\DboSource.php(1009): DboSource->execute('INSERT INTO `my...')
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Model\Model.php(1730): DboSource->create(Object(User), Array, Array)
#4 C:\xampp\htdocs\Exercicios_PHP\blog\app\Controller\UsersController.php(60): Model->save(Array)
#5 [internal function]: UsersController->register()
#6 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Controller\Controller.php(485): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#7 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#8 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#9 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2012-11-27 23:59:13 Error: [MissingControllerException] Controller class HelloController could not be found.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2012-11-28 00:00:01 Error: [MissingControllerException] Controller class HelloController could not be found.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2012-11-28 00:02:27 Error: [MissingControllerException] Controller class HelloController could not be found.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2012-11-28 00:04:28 Error: Fatal Error (4): syntax error, unexpected '{', expecting function (T_FUNCTION) in [C:\xampp\htdocs\Exercicios_PHP\blog\app\Controller\HelloController.php, line 2]
2012-11-28 00:04:28 Error: [FatalErrorException] syntax error, unexpected '{', expecting function (T_FUNCTION)
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 2)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 2, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 2, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-11-28 00:04:47 Error: Fatal Error (4): syntax error, unexpected '}', expecting ',' or ';' in [C:\xampp\htdocs\Exercicios_PHP\blog\app\Controller\HelloController.php, line 10]
2012-11-28 00:04:47 Error: [FatalErrorException] syntax error, unexpected '}', expecting ',' or ';'
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 10)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 10, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 10, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-11-28 00:05:04 Error: [MissingViewException] View file "C:\xampp\htdocs\Exercicios_PHP\blog\app\View\Hello\index.ctp" is missing.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\View\View.php(472): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Controller\Controller.php(957): View->render(NULL, NULL)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(193): Controller->render()
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(HelloController), Object(CakeRequest), Object(CakeResponse))
#4 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2012-11-28 00:11:53 Error: [MissingControllerException] Controller class SobremimController could not be found.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2012-11-28 21:29:03 Error: [MissingActionException] Action UsersController::index() could not be found.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2012-11-28 22:12:10 Error: Fatal Error (4): syntax error, unexpected '->' (T_OBJECT_OPERATOR) in [C:\xampp\htdocs\Exercicios_PHP\blog\app\Controller\PostsController.php, line 12]
2012-11-28 22:12:10 Error: [FatalErrorException] syntax error, unexpected '->' (T_OBJECT_OPERATOR)
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 12)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 12, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 12, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-11-28 22:12:16 Error: [MissingControllerException] Controller class PostController could not be found.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2012-11-28 22:12:43 Error: [MissingControllerException] Controller class PostController could not be found.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2012-11-28 22:12:56 Error: Fatal Error (4): syntax error, unexpected '->' (T_OBJECT_OPERATOR) in [C:\xampp\htdocs\Exercicios_PHP\blog\app\Controller\PostsController.php, line 12]
2012-11-28 22:12:56 Error: [FatalErrorException] syntax error, unexpected '->' (T_OBJECT_OPERATOR)
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 12)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 12, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 12, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-11-28 22:15:37 Error: Fatal Error (4): syntax error, unexpected '->' (T_OBJECT_OPERATOR) in [C:\xampp\htdocs\Exercicios_PHP\blog\app\Controller\PostsController.php, line 12]
2012-11-28 22:15:37 Error: [FatalErrorException] syntax error, unexpected '->' (T_OBJECT_OPERATOR)
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 12)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 12, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 12, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-11-28 22:15:39 Error: Fatal Error (4): syntax error, unexpected '->' (T_OBJECT_OPERATOR) in [C:\xampp\htdocs\Exercicios_PHP\blog\app\Controller\PostsController.php, line 12]
2012-11-28 22:15:39 Error: [FatalErrorException] syntax error, unexpected '->' (T_OBJECT_OPERATOR)
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 12)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 12, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 12, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-11-28 22:15:47 Error: Fatal Error (4): syntax error, unexpected '->' (T_OBJECT_OPERATOR) in [C:\xampp\htdocs\Exercicios_PHP\blog\app\Controller\PostsController.php, line 12]
2012-11-28 22:15:47 Error: [FatalErrorException] syntax error, unexpected '->' (T_OBJECT_OPERATOR)
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 12)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 12, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 12, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-11-28 22:17:08 Error: Fatal Error (4): syntax error, unexpected '}' in [C:\xampp\htdocs\Exercicios_PHP\blog\app\Model\Post.php, line 8]
2012-11-28 22:17:08 Error: [FatalErrorException] syntax error, unexpected '}'
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 8)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 8, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 8, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-11-28 22:17:33 Error: Fatal Error (4): syntax error, unexpected '}' in [C:\xampp\htdocs\Exercicios_PHP\blog\app\Model\Post.php, line 8]
2012-11-28 22:17:33 Error: [FatalErrorException] syntax error, unexpected '}'
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 8)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 8, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 8, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-11-28 22:43:24 Error: [MissingControllerException] Controller class ViewController could not be found.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2012-11-28 22:44:19 Error: [MissingViewException] View file "C:\xampp\htdocs\Exercicios_PHP\blog\app\View\Posts\view.ctp" is missing.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\View\View.php(472): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Controller\Controller.php(957): View->render(NULL, NULL)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(193): Controller->render()
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#4 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2012-11-28 22:46:24 Error: [MissingViewException] View file "C:\xampp\htdocs\Exercicios_PHP\blog\app\View\Posts\view.ctp" is missing.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\View\View.php(472): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Controller\Controller.php(957): View->render(NULL, NULL)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(193): Controller->render()
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#4 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2012-11-28 23:27:49 Error: Fatal Error (4): syntax error, unexpected end of file in [C:\xampp\htdocs\Exercicios_PHP\blog\app\Controller\PostsController.php, line 37]
2012-11-28 23:27:49 Error: [FatalErrorException] syntax error, unexpected end of file
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 37)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 37, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 37, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-11-28 23:28:24 Error: Fatal Error (4): syntax error, unexpected end of file in [C:\xampp\htdocs\Exercicios_PHP\blog\app\Controller\PostsController.php, line 40]
2012-11-28 23:28:24 Error: [FatalErrorException] syntax error, unexpected end of file
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 40)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 40, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 40, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-11-28 23:43:30 Error: Fatal Error (4): syntax error, unexpected '(', expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in [C:\xampp\htdocs\Exercicios_PHP\blog\app\View\Posts\index.ctp, line 29]
2012-11-28 23:43:30 Error: [FatalErrorException] syntax error, unexpected '(', expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$'
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 29)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 29, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 29, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-11-28 23:44:29 Error: Fatal Error (4): syntax error, unexpected '(', expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in [C:\xampp\htdocs\Exercicios_PHP\blog\app\View\Posts\index.ctp, line 29]
2012-11-28 23:44:29 Error: [FatalErrorException] syntax error, unexpected '(', expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$'
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 29)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 29, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 29, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-11-28 23:53:01 Error: Fatal Error (4): syntax error, unexpected end of file in [C:\xampp\htdocs\Exercicios_PHP\blog\app\View\Posts\index.ctp, line 37]
2012-11-28 23:53:01 Error: [FatalErrorException] syntax error, unexpected end of file
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 37)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 37, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 37, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-11-28 23:53:17 Error: Fatal Error (4): syntax error, unexpected end of file in [C:\xampp\htdocs\Exercicios_PHP\blog\app\View\Posts\index.ctp, line 37]
2012-11-28 23:53:17 Error: [FatalErrorException] syntax error, unexpected end of file
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 37)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 37, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 37, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-11-29 00:02:46 Error: Fatal Error (4): syntax error, unexpected '<' in [C:\xampp\htdocs\Exercicios_PHP\blog\app\View\Posts\index.ctp, line 25]
2012-11-29 00:02:46 Error: [FatalErrorException] syntax error, unexpected '<'
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 25)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 25, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 25, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-11-29 00:03:27 Error: Fatal Error (4): syntax error, unexpected '<' in [C:\xampp\htdocs\Exercicios_PHP\blog\app\View\Posts\index.ctp, line 59]
2012-11-29 00:03:27 Error: [FatalErrorException] syntax error, unexpected '<'
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 59)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 59, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 59, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-11-29 00:05:01 Error: Fatal Error (4): syntax error, unexpected '<' in [C:\xampp\htdocs\Exercicios_PHP\blog\app\View\Posts\index.ctp, line 59]
2012-11-29 00:05:01 Error: [FatalErrorException] syntax error, unexpected '<'
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 59)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 59, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 59, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-06 20:49:12 Error: [MissingControllerException] Controller class JsController could not be found.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2012-12-06 20:49:31 Error: [MissingActionException] Action HelloController::conta() could not be found.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(HelloController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2012-12-06 20:50:55 Error: [MissingControllerException] Controller class LocalhostController could not be found.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2012-12-06 21:11:46 Error: [MissingActionException] Action PostsController::edit() could not be found.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2012-12-06 21:13:10 Error: Fatal Error (4): syntax error, unexpected end of file, expecting function (T_FUNCTION) in [C:\xampp\htdocs\Exercicios_PHP\blog\app\Controller\PostsController.php, line 52]
2012-12-06 21:13:10 Error: [FatalErrorException] syntax error, unexpected end of file, expecting function (T_FUNCTION)
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 52)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 52, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 52, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-06 21:13:15 Error: Fatal Error (4): syntax error, unexpected end of file, expecting function (T_FUNCTION) in [C:\xampp\htdocs\Exercicios_PHP\blog\app\Controller\PostsController.php, line 52]
2012-12-06 21:13:15 Error: [FatalErrorException] syntax error, unexpected end of file, expecting function (T_FUNCTION)
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 52)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 52, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 52, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-06 21:13:31 Error: Fatal Error (4): syntax error, unexpected end of file, expecting function (T_FUNCTION) in [C:\xampp\htdocs\Exercicios_PHP\blog\app\Controller\PostsController.php, line 52]
2012-12-06 21:13:31 Error: [FatalErrorException] syntax error, unexpected end of file, expecting function (T_FUNCTION)
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 52)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 52, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 52, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-06 21:16:12 Error: Fatal Error (4): syntax error, unexpected end of file, expecting function (T_FUNCTION) in [C:\xampp\htdocs\Exercicios_PHP\blog\app\Controller\PostsController.php, line 52]
2012-12-06 21:16:12 Error: [FatalErrorException] syntax error, unexpected end of file, expecting function (T_FUNCTION)
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 52)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 52, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 52, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-06 21:45:43 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\Exercicios_PHP\blog\app\View\Posts\index.ctp, line 36]
2012-12-06 21:45:43 Error: [FatalErrorException] syntax error, unexpected ';'
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 36)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 36, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 36, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-06 21:48:41 Error: Fatal Error (4): syntax error, unexpected 'array' (T_ARRAY) in [C:\xampp\htdocs\Exercicios_PHP\blog\app\View\Posts\index.ctp, line 41]
2012-12-06 21:48:41 Error: [FatalErrorException] syntax error, unexpected 'array' (T_ARRAY)
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 41)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 41, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 41, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-06 22:46:54 Error: [MissingActionException] Action UsersController::index() could not be found.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2012-12-06 22:47:44 Error: [MissingActionException] Action UsersController::index() could not be found.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2012-12-06 22:48:09 Error: [MissingActionException] Action UsersController::index() could not be found.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2012-12-06 22:55:17 Error: [MissingActionException] Action UsersController::index() could not be found.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2012-12-06 23:15:09 Error: [MissingActionException] Action UsersController::index() could not be found.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2012-12-06 23:20:36 Error: [MissingActionException] Action UsersController::index() could not be found.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2012-12-06 23:20:39 Error: [MissingControllerException] Controller class TarefasController could not be found.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2012-12-06 23:20:50 Error: [MissingControllerException] Controller class TarefasController could not be found.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2012-12-06 23:23:35 Error: [MissingControllerException] Controller class TarefasController could not be found.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2012-12-06 23:23:39 Error: [MissingActionException] Action UsersController::PostsController() could not be found.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2012-12-06 23:24:38 Error: [MissingActionException] Action UsersController::PostsController() could not be found.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2012-12-06 23:24:42 Error: [MissingViewException] View file "C:\xampp\htdocs\Exercicios_PHP\blog\app\View\Users\postagem.ctp" is missing.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\View\View.php(472): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Controller\Controller.php(957): View->render(NULL, NULL)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(193): Controller->render()
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#4 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2012-12-06 23:25:56 Error: Fatal Error (4): syntax error, unexpected '->' (T_OBJECT_OPERATOR) in [C:\xampp\htdocs\Exercicios_PHP\blog\app\Controller\UsersController.php, line 242]
2012-12-06 23:25:56 Error: [FatalErrorException] syntax error, unexpected '->' (T_OBJECT_OPERATOR)
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 242)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 242, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 242, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-06 23:25:59 Error: Fatal Error (4): syntax error, unexpected '->' (T_OBJECT_OPERATOR) in [C:\xampp\htdocs\Exercicios_PHP\blog\app\Controller\UsersController.php, line 242]
2012-12-06 23:25:59 Error: [FatalErrorException] syntax error, unexpected '->' (T_OBJECT_OPERATOR)
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 242)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 242, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 242, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-06 23:26:00 Error: Fatal Error (4): syntax error, unexpected '->' (T_OBJECT_OPERATOR) in [C:\xampp\htdocs\Exercicios_PHP\blog\app\Controller\UsersController.php, line 242]
2012-12-06 23:26:00 Error: [FatalErrorException] syntax error, unexpected '->' (T_OBJECT_OPERATOR)
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 242)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 242, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 242, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-06 23:26:01 Error: Fatal Error (4): syntax error, unexpected '->' (T_OBJECT_OPERATOR) in [C:\xampp\htdocs\Exercicios_PHP\blog\app\Controller\UsersController.php, line 242]
2012-12-06 23:26:01 Error: [FatalErrorException] syntax error, unexpected '->' (T_OBJECT_OPERATOR)
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 242)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 242, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 242, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-06 23:26:17 Error: Fatal Error (4): syntax error, unexpected '->' (T_OBJECT_OPERATOR) in [C:\xampp\htdocs\Exercicios_PHP\blog\app\Controller\UsersController.php, line 242]
2012-12-06 23:26:17 Error: [FatalErrorException] syntax error, unexpected '->' (T_OBJECT_OPERATOR)
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 242)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 242, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 242, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-06 23:26:19 Error: Fatal Error (4): syntax error, unexpected '->' (T_OBJECT_OPERATOR) in [C:\xampp\htdocs\Exercicios_PHP\blog\app\Controller\UsersController.php, line 242]
2012-12-06 23:26:19 Error: [FatalErrorException] syntax error, unexpected '->' (T_OBJECT_OPERATOR)
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 242)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 242, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 242, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-06 23:26:22 Error: Fatal Error (4): syntax error, unexpected '->' (T_OBJECT_OPERATOR) in [C:\xampp\htdocs\Exercicios_PHP\blog\app\Controller\UsersController.php, line 242]
2012-12-06 23:26:22 Error: [FatalErrorException] syntax error, unexpected '->' (T_OBJECT_OPERATOR)
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 242)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 242, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 242, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-06 23:26:25 Error: Fatal Error (4): syntax error, unexpected '->' (T_OBJECT_OPERATOR) in [C:\xampp\htdocs\Exercicios_PHP\blog\app\Controller\UsersController.php, line 242]
2012-12-06 23:26:25 Error: [FatalErrorException] syntax error, unexpected '->' (T_OBJECT_OPERATOR)
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 242)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 242, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 242, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-06 23:26:27 Error: Fatal Error (4): syntax error, unexpected '->' (T_OBJECT_OPERATOR) in [C:\xampp\htdocs\Exercicios_PHP\blog\app\Controller\UsersController.php, line 242]
2012-12-06 23:26:27 Error: [FatalErrorException] syntax error, unexpected '->' (T_OBJECT_OPERATOR)
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 242)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 242, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 242, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-06 23:26:27 Error: Fatal Error (4): syntax error, unexpected '->' (T_OBJECT_OPERATOR) in [C:\xampp\htdocs\Exercicios_PHP\blog\app\Controller\UsersController.php, line 242]
2012-12-06 23:26:27 Error: [FatalErrorException] syntax error, unexpected '->' (T_OBJECT_OPERATOR)
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 242)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 242, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 242, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-06 23:26:28 Error: Fatal Error (4): syntax error, unexpected '->' (T_OBJECT_OPERATOR) in [C:\xampp\htdocs\Exercicios_PHP\blog\app\Controller\UsersController.php, line 242]
2012-12-06 23:26:28 Error: [FatalErrorException] syntax error, unexpected '->' (T_OBJECT_OPERATOR)
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 242)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 242, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 242, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-06 23:28:33 Error: [MissingActionException] Action UsersController::users() could not be found.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2012-12-06 23:30:43 Error: [MissingActionException] Action UsersController::users() could not be found.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2012-12-06 23:30:47 Error: [MissingActionException] Action UsersController::users() could not be found.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2012-12-06 23:30:50 Error: [MissingActionException] Action UsersController::users() could not be found.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2012-12-06 23:31:52 Error: [MissingActionException] Action UsersController::users() could not be found.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2012-12-06 23:31:55 Error: [MissingActionException] Action UsersController::users() could not be found.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2012-12-06 23:32:10 Error: [MissingActionException] Action UsersController::users() could not be found.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2012-12-06 23:32:55 Error: [MissingActionException] Action UsersController::users() could not be found.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2012-12-06 23:33:04 Error: [MissingActionException] Action UsersController::users() could not be found.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2012-12-06 23:33:07 Error: [MissingActionException] Action UsersController::users() could not be found.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2012-12-06 23:34:51 Error: [MissingActionException] Action UsersController::Posts() could not be found.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2012-12-06 23:35:54 Error: [MissingActionException] Action UsersController::Posts() could not be found.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2012-12-06 23:35:58 Error: [MissingActionException] Action UsersController::Posts() could not be found.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2012-12-06 23:36:01 Error: [MissingActionException] Action UsersController::Posts() could not be found.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2012-12-06 23:36:51 Error: [MissingActionException] Action UsersController::Posts() could not be found.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2012-12-06 23:38:37 Error: [MissingActionException] Action UsersController::Posts() could not be found.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2012-12-06 23:38:42 Error: [MissingActionException] Action PostsController::posts() could not be found.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2012-12-06 23:41:26 Error: [MissingActionException] Action PostsController::posts() could not be found.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2012-12-06 23:41:29 Error: [MissingActionException] Action PostsController::posts() could not be found.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2012-12-08 17:14:16 Error: [MissingControllerException] Controller class PcsController could not be found.
#0 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2012-12-08 17:42:06 Error: Fatal Error (64): Cannot redeclare class Pcs in [C:\xampp\htdocs\Exercicios_PHP\blog\app\Model\Pc.php, line 4]
2012-12-08 17:42:06 Error: [FatalErrorException] Cannot redeclare class Pcs
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 4)
#1 [internal function]: ErrorHandler::handleError(64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 4, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 4, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-08 17:42:10 Error: Fatal Error (64): Cannot redeclare class Pcs in [C:\xampp\htdocs\Exercicios_PHP\blog\app\Model\Pc.php, line 4]
2012-12-08 17:42:10 Error: [FatalErrorException] Cannot redeclare class Pcs
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 4)
#1 [internal function]: ErrorHandler::handleError(64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 4, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 4, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-08 17:42:10 Error: Fatal Error (64): Cannot redeclare class Pcs in [C:\xampp\htdocs\Exercicios_PHP\blog\app\Model\Pc.php, line 4]
2012-12-08 17:42:10 Error: [FatalErrorException] Cannot redeclare class Pcs
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 4)
#1 [internal function]: ErrorHandler::handleError(64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 4, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 4, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-08 18:08:49 Error: Fatal Error (4): syntax error, unexpected end of file, expecting function (T_FUNCTION) in [C:\xampp\htdocs\Exercicios_PHP\blog\app\Controller\PcsController.php, line 44]
2012-12-08 18:08:49 Error: [FatalErrorException] syntax error, unexpected end of file, expecting function (T_FUNCTION)
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 44)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 44, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 44, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-08 18:08:55 Error: Fatal Error (4): syntax error, unexpected end of file, expecting function (T_FUNCTION) in [C:\xampp\htdocs\Exercicios_PHP\blog\app\Controller\PcsController.php, line 44]
2012-12-08 18:08:55 Error: [FatalErrorException] syntax error, unexpected end of file, expecting function (T_FUNCTION)
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 44)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 44, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 44, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-08 18:11:02 Error: Fatal Error (4): syntax error, unexpected end of file, expecting function (T_FUNCTION) in [C:\xampp\htdocs\Exercicios_PHP\blog\app\Controller\PcsController.php, line 44]
2012-12-08 18:11:02 Error: [FatalErrorException] syntax error, unexpected end of file, expecting function (T_FUNCTION)
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 44)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 44, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 44, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-08 18:11:14 Error: Fatal Error (64): Cannot redeclare class Pcs in [C:\xampp\htdocs\Exercicios_PHP\blog\app\Model\Pc.php, line 4]
2012-12-08 18:11:14 Error: [FatalErrorException] Cannot redeclare class Pcs
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 4)
#1 [internal function]: ErrorHandler::handleError(64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 4, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 4, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-08 18:13:07 Error: Fatal Error (64): Cannot redeclare class Pcs in [C:\xampp\htdocs\Exercicios_PHP\blog\app\Model\Pc.php, line 4]
2012-12-08 18:13:07 Error: [FatalErrorException] Cannot redeclare class Pcs
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 4)
#1 [internal function]: ErrorHandler::handleError(64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 4, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 4, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-08 18:13:20 Error: Fatal Error (4): syntax error, unexpected '}' in [C:\xampp\htdocs\Exercicios_PHP\blog\app\Controller\PcsController.php, line 43]
2012-12-08 18:13:20 Error: [FatalErrorException] syntax error, unexpected '}'
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 43)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 43, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 43, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-08 18:13:51 Error: Fatal Error (64): Cannot redeclare class Pcs in [C:\xampp\htdocs\Exercicios_PHP\blog\app\Model\Pc.php, line 4]
2012-12-08 18:13:51 Error: [FatalErrorException] Cannot redeclare class Pcs
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 4)
#1 [internal function]: ErrorHandler::handleError(64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 4, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 4, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-08 18:18:55 Error: Fatal Error (64): Cannot redeclare class Pcs in [C:\xampp\htdocs\Exercicios_PHP\blog\app\Model\Pc.php, line 4]
2012-12-08 18:18:55 Error: [FatalErrorException] Cannot redeclare class Pcs
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 4)
#1 [internal function]: ErrorHandler::handleError(64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 4, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 4, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-08 18:20:15 Error: Fatal Error (4): syntax error, unexpected 'public' (T_PUBLIC) in [C:\xampp\htdocs\Exercicios_PHP\blog\app\Controller\PcsController.php, line 8]
2012-12-08 18:20:15 Error: [FatalErrorException] syntax error, unexpected 'public' (T_PUBLIC)
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 8)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 8, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 8, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-08 18:20:32 Error: Fatal Error (64): Cannot redeclare class Pcs in [C:\xampp\htdocs\Exercicios_PHP\blog\app\Model\Pc.php, line 4]
2012-12-08 18:20:32 Error: [FatalErrorException] Cannot redeclare class Pcs
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 4)
#1 [internal function]: ErrorHandler::handleError(64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 4, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 4, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-08 18:23:14 Error: Fatal Error (64): Cannot redeclare class Pcs in [C:\xampp\htdocs\Exercicios_PHP\blog\app\Model\Pc.php, line 4]
2012-12-08 18:23:14 Error: [FatalErrorException] Cannot redeclare class Pcs
#0 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 4)
#1 [internal function]: ErrorHandler::handleError(64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 4, Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 4, Array)
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-08 18:35:28 Error: [MethodNotAllowedException] Method Not Allowed
#0 [internal function]: PcsController->delete('3')
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Controller\Controller.php(485): ReflectionMethod->invokeArgs(Object(PcsController), Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(PcsController), Object(CakeRequest), Object(CakeResponse))
#4 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2012-12-08 18:41:26 Error: [MethodNotAllowedException] Method Not Allowed
#0 [internal function]: PcsController->delete('1')
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Controller\Controller.php(485): ReflectionMethod->invokeArgs(Object(PcsController), Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(PcsController), Object(CakeRequest), Object(CakeResponse))
#4 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2012-12-08 18:49:53 Error: [MethodNotAllowedException] Method Not Allowed
#0 [internal function]: PcsController->delete('3')
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Controller\Controller.php(485): ReflectionMethod->invokeArgs(Object(PcsController), Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(PcsController), Object(CakeRequest), Object(CakeResponse))
#4 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2012-12-08 19:09:22 Error: [MethodNotAllowedException] Method Not Allowed
#0 [internal function]: PcsController->delete('3')
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Controller\Controller.php(485): ReflectionMethod->invokeArgs(Object(PcsController), Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(PcsController), Object(CakeRequest), Object(CakeResponse))
#4 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2012-12-08 19:10:19 Error: [MethodNotAllowedException] Method Not Allowed
#0 [internal function]: PcsController->delete('5')
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Controller\Controller.php(485): ReflectionMethod->invokeArgs(Object(PcsController), Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(PcsController), Object(CakeRequest), Object(CakeResponse))
#4 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2012-12-08 19:11:32 Error: [MethodNotAllowedException] Method Not Allowed
#0 [internal function]: PcsController->delete('5')
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Controller\Controller.php(485): ReflectionMethod->invokeArgs(Object(PcsController), Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(PcsController), Object(CakeRequest), Object(CakeResponse))
#4 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2012-12-08 19:11:36 Error: [MethodNotAllowedException] Method Not Allowed
#0 [internal function]: PcsController->delete('5')
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Controller\Controller.php(485): ReflectionMethod->invokeArgs(Object(PcsController), Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(PcsController), Object(CakeRequest), Object(CakeResponse))
#4 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2012-12-08 19:11:59 Error: [MethodNotAllowedException] Method Not Allowed
#0 [internal function]: PcsController->delete('5')
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Controller\Controller.php(485): ReflectionMethod->invokeArgs(Object(PcsController), Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(PcsController), Object(CakeRequest), Object(CakeResponse))
#4 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2012-12-08 19:12:28 Error: [MethodNotAllowedException] Method Not Allowed
#0 [internal function]: PcsController->delete('5')
#1 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Controller\Controller.php(485): ReflectionMethod->invokeArgs(Object(PcsController), Array)
#2 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\Exercicios_PHP\blog\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(PcsController), Object(CakeRequest), Object(CakeResponse))
#4 C:\xampp\htdocs\Exercicios_PHP\blog\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
